# Generated by Django 4.1 on 2023-12-08 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_titulo", models.CharField(max_length=255)),
                ("cert_emisor", models.CharField(max_length=255)),
                ("cert_receptor", models.CharField(max_length=255)),
                ("cert_fecha_emision", models.DateField()),
                ("cert_descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ConsultaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("con_med_diagnostico", models.TextField()),
                ("con_med_recomendaciones", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_per_nombre_completo", models.CharField(max_length=255)),
                ("med_per_credenciales", models.TextField()),
                ("med_per_especialidades", models.TextField()),
                ("med_per_horarios_consulta", models.TextField()),
                ("med_per_informacion_contacto", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usu_cedula", models.CharField(max_length=20, unique=True)),
                ("usu_nombre_completo", models.CharField(max_length=255)),
                ("usu_numero_telefono", models.CharField(max_length=20)),
                (
                    "usu_correo_electronico",
                    models.EmailField(max_length=254, unique=True),
                ),
                ("usu_direccion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rep_tipo_reporte", models.CharField(max_length=100)),
                ("rep_parametros", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescripcionOrdenMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pres_ord_nombre_paciente", models.CharField(max_length=255)),
                (
                    "pres_ord_fecha_emision",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("pres_ord_detalles_prescripcion", models.TextField()),
                ("pres_ord_estado_cumplimiento", models.CharField(max_length=100)),
                (
                    "consulta_medica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.consultamedica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanCuentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_cue_fecha_transaccion",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("plan_cue_tipo_transaccion", models.CharField(max_length=100)),
                (
                    "plan_cue_monto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("plan_cue_descripcion", models.TextField()),
                ("plan_cue_numero_referencia", models.CharField(max_length=100)),
                ("plan_cue_cuenta_destino", models.CharField(max_length=100)),
                ("plan_cue_metodo_pago", models.CharField(max_length=100)),
                ("plan_cue_categoria_gasto_ingreso", models.CharField(max_length=100)),
                ("plan_cue_datos_proveedor_cliente", models.TextField()),
                (
                    "consulta_medica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.consultamedica",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("perf_acc_nivel_acceso", models.CharField(max_length=50)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pac_nombre_completo", models.CharField(max_length=255)),
                (
                    "pac_fecha_nacimiento",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("pac_genero", models.CharField(max_length=50)),
                ("pac_direccion", models.TextField()),
                ("pac_numero_telefono", models.CharField(max_length=20)),
                (
                    "pac_correo_electronico",
                    models.EmailField(max_length=254, unique=True),
                ),
                ("pac_antecedentes_medicos", models.TextField(blank=True)),
                ("pac_enfermedades", models.TextField(blank=True)),
                ("pac_alergias", models.TextField(blank=True)),
                ("pac_medicamentos_actuales", models.TextField(blank=True)),
                (
                    "medico_personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.medicopersonal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="medicopersonal",
            name="reportes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CitasMed.reporte"
            ),
        ),
        migrations.CreateModel(
            name="IntegracionContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integ_cont_datos_financieros", models.TextField()),
                (
                    "plan_cuentas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.plancuentas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facturacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_nombre_paciente", models.CharField(max_length=255)),
                ("fact_numero_identificacion", models.CharField(max_length=20)),
                ("fact_numero_poliza_seguro", models.CharField(max_length=20)),
                ("fact_detalles_facturacion", models.TextField()),
                ("fact_estado_pago", models.CharField(max_length=100)),
                ("fact_metodo_pago", models.CharField(max_length=100)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CitasMed.paciente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultamedica",
            name="con_med_medico_personal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CitasMed.medicopersonal",
            ),
        ),
        migrations.AddField(
            model_name="consultamedica",
            name="con_med_paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CitasMed.paciente"
            ),
        ),
    ]
