# Generated by Django 4.1 on 2024-01-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CitasMed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usu_correo_electronico",
            field=models.TextField(),
        ),
    ]
