# Generated by Django 4.1 on 2024-01-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CitasMed", "0002_alter_usuario_usu_correo_electronico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicopersonal",
            name="reportes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CitasMed.reporte",
            ),
        ),
    ]
