# Generated by Django 4.1 on 2024-01-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CitasMed", "0003_alter_medicopersonal_reportes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificado",
            name="cert_fecha_emision",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="pac_fecha_nacimiento",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plancuentas",
            name="plan_cue_fecha_transaccion",
            field=models.CharField(max_length=255),
        ),
    ]
